### ISSUE TITLE
Add a project license

### ISSUE THREAD

**Issue by GeoTob** [terrestris/geoserver-notification-http#1]
@hwbllmnn - have found this small but quite useful extension to GeoServer and would like to use it with some of our GS deployments. Would you consider adding an Open Source license file to the project so that we and others are able to use and modify the code?

**Comment by hwbllmnn** [comment]
Done. Feel free to submit pull requests if you modify the code :-)

**Comment by GeoTob** [comment]
Awesome!  and will gladly submit PRs !
